name: satu
description: A new Flutter project.

publish_to: 'none'

version: 1.0.5+34

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  get: ^4.6.5
  responsive_sizer: ^3.2.0
  shared_preferences: ^2.0.20
  flutter_svg: ^2.0.7
  load: ^1.0.0
  loading_indicator: ^3.1.1
  get_storage: ^2.1.1
  device_info_plus: ^9.0.0
  package_info_plus: ^4.1.0
  sqflite: 2.3.0
  sqflite_sqlcipher: 2.2.1
  dio: ^5.1.2
  cached_network_image: ^3.2.3
  uuid: ^3.0.7
  mobile_scanner: ^3.4.1
  # image_picker: ^1.1.2
  dio_http2_adapter: ^2.3.1
  device_orientation: ^0.0.1
  change_app_package_name: ^1.1.0
  photo_view: ^0.14.0
  url_launcher: ^6.3.0
  flutter_inappwebview: ^6.0.0
  camera: ^0.11.0+1
  syncfusion_flutter_signaturepad: ^27.1.48

  
dependency_overrides:
  flutter_inappwebview_ios:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: 27fd339172572fe1b16cdcdae235b2a88f432e3c
      path: flutter_inappwebview_ios
  win32: ^5.5.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
      - assets/image/
      - assets/fonts/
      - assets/logo/
      - assets/icon/
