name: satu
description: A new Flutter project.

publish_to: 'none'

version: 1.0.9+39

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  # google_fonts: ^6.1.0  # Removed to avoid Google SDK privacy manifest issues
  get: ^4.6.6
  responsive_sizer: ^3.3.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  load: ^1.0.0
  loading_indicator: ^3.1.1
  get_storage: ^2.1.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  sqflite: ^2.3.2
  sqflite_sqlcipher: ^2.2.1
  dio: ^5.4.0
  cached_network_image: ^3.3.0
  uuid: ^4.3.3
  mobile_scanner: ^4.0.1
  # image_picker: ^1.1.2
  dio_http2_adapter: ^2.5.0
  device_orientation: ^0.0.1
  change_app_package_name: ^1.1.0
  photo_view: ^0.14.0
  url_launcher: ^6.2.4
  flutter_inappwebview: ^6.0.0
  camera: ^0.11.0+1
  syncfusion_flutter_signaturepad: ^27.1.48

dependency_overrides:
  flutter_inappwebview_ios:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: 27fd339172572fe1b16cdcdae235b2a88f432e3c
      path: flutter_inappwebview_ios
  win32: ^5.5.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
      - assets/image/
      - assets/fonts/
      - assets/logo/
      - assets/icon/
